// Autogenerated TypeScript style map converted from CSS classes

import { createGlobalStyle } from 'styled-components';

export type CSSValue = string | number;
export interface StyleObject {
  [property: string]: CSSValue | StyleObject;
}

export interface Styles {
  [selector: string]: StyleObject;
}

const styles: Styles = {
  // Global
  global: {
    '*': {
      margin: 0,
      padding: 0,
      boxSizing: 'border-box',
    },
    body: {
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      backgroundColor: '#f3f4f6',
      color: '#374151',
    },
  },

  // Header
  header: {
    backgroundColor: '#374151',
    color: 'white',
    padding: '12px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  logo: {
    backgroundColor: '#dc2626',
    color: 'white',
    padding: '8px 16px',
    borderRadius: '4px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  searchContainer: { position: 'relative' },
  searchInput: {
    backgroundColor: '#4b5563',
    color: 'white',
    padding: '8px 12px 8px 40px',
    border: 'none',
    borderRadius: '4px',
    width: '300px',
    outline: 'none',
    '::placeholder': { color: '#9ca3af' },
  },
  searchIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '16px',
    height: '16px',
    opacity: 0.6,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    fontSize: '14px',
  },
  statusBadge: {
    backgroundColor: '#10b981',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },

  // Layout
  container: { display: 'flex', minHeight: 'calc(100vh - 56px)' },
  sidebar: { width: '256px', backgroundColor: 'white', boxShadow: '2px 0 8px rgba(0,0,0,0.1)' },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 24px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '14px',
    color: '#6b7280',
    ':hover': { backgroundColor: '#f3f4f6' },
    '&.active': { backgroundColor: '#dc2626', color: 'white', fontWeight: 600 },
  },

  // Main Content
  mainContent: { flex: 1, padding: '24px' },
  pageHeader: { marginBottom: '24px' },
  pageTitle: { fontSize: '24px', fontWeight: 600, marginBottom: '8px' },
  pageSubtitle: { color: '#6b7280', fontSize: '14px' },

  // KPI Cards
  kpiGrid: { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '16px', marginBottom: '24px' },
  kpiCard: { backgroundColor: 'white', padding: '16px', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', textAlign: 'center' },
  kpiIcon: { fontSize: '24px', marginBottom: '8px' },
  kpiValue: { fontSize: '24px', fontWeight: 'bold', color: '#374151', marginBottom: '4px' },
  kpiLabel: { fontSize: '12px', color: '#6b7280', textTransform: 'uppercase' },

  // Grid / Card
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' },
  card: { backgroundColor: 'white', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', padding: '24px' },
  cardHeader: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', paddingBottom: '16px', borderBottom: '1px solid #e5e7eb',
  },
  cardTitle: { fontSize: '16px', fontWeight: 600, color: '#374151' },

  // Map
  mapContainer: {
    height: '600px',
    backgroundColor: '#1f2937',
    borderRadius: '8px',
    position: 'relative',
    overflow: 'hidden',
    backgroundImage:
      'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),\n      linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)',
    backgroundSize: '20px 20px',
  },
  mapControls: { position: 'absolute', top: '10px', right: '10px', display: 'flex', flexDirection: 'column', gap: '8px', zIndex: 20 },
  mapBtn: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    border: 'none',
    padding: '8px',
    borderRadius: '4px',
    cursor: 'pointer',
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    transition: 'all 0.2s',
    ':hover': { backgroundColor: 'white', transform: 'scale(1.05)' },
  },
  revenueZone: {
    position: 'absolute',
    border: '2px solid rgba(255,255,255,0.3)',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    fontWeight: 600,
    color: 'white',
    textAlign: 'center',
    ':hover': { transform: 'scale(1.05)', zIndex: 10, borderColor: 'white' },
  },
  revenueHighest: { backgroundColor: 'rgba(220,38,38,0.8)' },
  revenueHigh: { backgroundColor: 'rgba(245,158,11,0.8)' },
  revenueMedium: { backgroundColor: 'rgba(251,191,36,0.8)' },
  revenueStandard: { backgroundColor: 'rgba(34,197,94,0.8)' },
  revenueLow: { backgroundColor: 'rgba(59,130,246,0.8)' },

  // Form
  formSection: { marginBottom: '24px' },
  formSectionTitle: { fontSize: '14px', fontWeight: 600, color: '#374151', marginBottom: '12px', textTransform: 'uppercase' },
  formGroup: { marginBottom: '16px' },
  formLabel: { display: 'block', fontSize: '14px', fontWeight: 500, color: '#374151', marginBottom: '4px' },
  formLabelRequired: { '::after': { content: '" *"', color: '#dc2626' } },
  formInput: {
    width: '100%', padding: '8px 12px', border: '1px solid #e5e7eb', borderRadius: '4px', fontSize: '14px', transition: 'border-color 0.2s',
    ':focus': { outline: 'none', borderColor: '#dc2626' },
  },
  formSelect: { width: '100%', padding: '8px 12px', border: '1px solid #e5e7eb', borderRadius: '4px', fontSize: '14px', backgroundColor: 'white', cursor: 'pointer' },

  // Buttons
  btn: { padding: '10px 20px', border: 'none', borderRadius: '4px', fontSize: '14px', fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s', textTransform: 'uppercase' },
  btnPrimary: { backgroundColor: '#dc2626', color: 'white', ':hover': { backgroundColor: '#b91c1c' } },
  btnSecondary: { backgroundColor: 'white', color: '#374151', border: '1px solid #e5e7eb', ':hover': { backgroundColor: '#f3f4f6' } },
  btnIcon: { display: 'inline-flex', alignItems: 'center', gap: '8px' },

  // Revenue source tags
  revenueSourceTags: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '12px' },
  sourceTag: {
    backgroundColor: '#e5e7eb', color: '#374151', padding: '6px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 500, cursor: 'pointer', transition: 'all 0.2s',
    ':hover': { backgroundColor: '#d1d5db' },
    '&.active': { backgroundColor: '#dc2626', color: 'white' },
  },

  // COA Compliance Box
  coaBox: {
    backgroundColor: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: '6px', padding: '12px', marginBottom: '16px', fontSize: '13px', color: '#1e40af', display: 'flex', alignItems: 'center', gap: '8px',
  },

  // Revenue table
  revenueTable: {
    width: '100%', borderCollapse: 'collapse', fontSize: '13px', marginTop: '16px',
    th: {
      backgroundColor: '#f3f4f6', padding: '8px 12px', textAlign: 'left', fontWeight: 600, color: '#374151', borderBottom: '1px solid #e5e7eb',
    },
    td: { padding: '8px 12px', borderBottom: '1px solid #f3f4f6' },
    'tr:hover': { backgroundColor: '#f9fafb' },
  },

  // Performance badge
  performanceBadge: { display: 'inline-block', padding: '2px 8px', borderRadius: '12px', fontSize: '11px', fontWeight: 600 },
  badgeExcellent: { backgroundColor: '#d1fae5', color: '#065f46' },
  badgeGood: { backgroundColor: '#dbeafe', color: '#1e40af' },
  badgeAverage: { backgroundColor: '#fef3c7', color: '#92400e' },
  badgeNeedsImprovement: { backgroundColor: '#fee2e2', color: '#991b1b' },

  // Legend
  legend: { display: 'flex', justifyContent: 'center', gap: '24px', padding: '16px', backgroundColor: '#f9fafb', borderRadius: '6px', marginTop: '16px' },
  legendItem: {
    display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', cursor: 'pointer', padding: '4px', borderRadius: '4px', transition: 'background-color 0.2s',
    ':hover': { backgroundColor: '#f3f4f6' },
    '&.disabled': { opacity: 0.5 },
    '&.disabled .legend-dot': { background: '#e5e7eb !important' },
  },
  legendColor: { width: '20px', height: '20px', borderRadius: '4px' },
  legendDot: { width: '12px', height: '12px', borderRadius: '50%', flexShrink: 0 },
  legendLabel: { flex: 1, color: '#374151' },
  legendValue: { fontWeight: 600, color: '#111827' },

  // Full width
  fullWidth: { gridColumn: '1 / -1' },

  // Workflow
  workflowContainer: { backgroundColor: '#f9fafb', borderRadius: '8px', padding: '16px', marginBottom: '16px' },
  workflowHeader: { fontSize: '12px', fontWeight: 600, color: '#6b7280', textTransform: 'uppercase', marginBottom: '12px' },
  workflowSteps: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'relative' },
  workflowStep: { textAlign: 'center', flex: 1 },
  stepIcon: { width: '40px', height: '40px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 8px', fontSize: '18px', fontWeight: 'bold' },
  stepIconCompleted: { backgroundColor: '#10b981', color: 'white' },
  stepIconActive: { backgroundColor: '#dc2626', color: 'white' },
  stepIconPending: { backgroundColor: '#e5e7eb', color: '#9ca3af' },
  stepLabel: { fontSize: '12px', fontWeight: 600, color: '#374151' },
  workflowLine: { position: 'absolute', height: '2px', backgroundColor: '#e5e7eb', top: '20px', left: '33%', right: '33%', zIndex: -1 },
  workflowLineActive: { backgroundColor: '#10b981', width: '33%' },

  // Quick stats
  quickStats: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '16px' },
  statCard: { backgroundColor: '#f9fafb', padding: '12px', borderRadius: '6px', textAlign: 'center' },
  statValue: { fontSize: '20px', fontWeight: 'bold', color: '#374151' },
  statLabel: { fontSize: '11px', color: '#6b7280', textTransform: 'uppercase', marginTop: '4px' },

  // Date range
  dateRangeGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },

  // Trend chart
  trendChartSection: { marginTop: '20px', backgroundColor: 'white', borderRadius: '8px', padding: '20px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', border: '1px solid #e5e7eb' },
  trendChartHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
  trendChartTitle: { fontSize: '18px', fontWeight: 600, color: '#111827', margin: 0 },
  trendChartControls: { display: 'flex', gap: '8px', alignItems: 'center' },
  trendSelect: { padding: '6px 12px', border: '1px solid #e5e7eb', borderRadius: '4px', fontSize: '13px', backgroundColor: 'white', cursor: 'pointer' },
  trendBtn: { padding: '6px 10px', border: '1px solid #e5e7eb', borderRadius: '4px', backgroundColor: 'white', cursor: 'pointer', fontSize: '16px', transition: 'all 0.2s', ':hover': { backgroundColor: '#f3f4f6', transform: 'translateY(-1px)' } },
  trendSummaryCards: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '20px' },
  trendCard: { backgroundColor: '#f9fafb', padding: '12px', borderRadius: '6px', textAlign: 'center', cursor: 'pointer', transition: 'all 0.2s', ':hover': { backgroundColor: '#f3f4f6', transform: 'translateY(-2px)', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' } },
  trendCardValue: { fontSize: '20px', fontWeight: 700, color: '#111827', marginBottom: '4px' },
  trendCardLabel: { fontSize: '11px', color: '#6b7280', textTransform: 'uppercase' },
  trendCardSublabel: { fontSize: '11px', color: '#374151', marginTop: '2px' },
  trendCardChange: { fontSize: '12px', fontWeight: 600, marginTop: '4px' },
  trendCardChangePositive: { color: '#10b981' },
  trendCardChangeNegative: { color: '#ef4444' },
  chartWrapper: { position: 'relative', height: '350px', marginBottom: '20px', padding: '10px', backgroundColor: '#fcfcfc', borderRadius: '6px', border: '1px solid #f3f4f6' },
  chartLegendGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', padding: '16px', backgroundColor: '#f9fafb', borderRadius: '6px' },

  // Revenue code list
  revenueCodeList: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px', marginTop: '8px' },
  revenueCodeItem: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px' },
  revenueCodeCheckbox: { cursor: 'pointer' },

  // Media queries
  '@media (max-width: 1024px)': {
    trendSummaryCards: { gridTemplateColumns: 'repeat(2, 1fr)' },
    chartLegendGrid: { gridTemplateColumns: 'repeat(2, 1fr)' },
  },
  '@media (max-width: 768px)': {
    trendChartControls: { flexWrap: 'wrap' },
    chartWrapper: { height: '250px' },
    trendSummaryCards: { gridTemplateColumns: 'repeat(2, 1fr)' },
    chartLegendGrid: { gridTemplateColumns: '1fr' },
  },
};

export default styles;

// Exact CSS replicated as GlobalStyle to ensure 1:1 visual parity
export const GlobalStyle = createGlobalStyle`
  * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
  }

  body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background-color: #f3f4f6;
      color: #374151;
  }

  /* Header Styles */
  .header {
      background-color: #374151;
      color: white;
      padding: 12px 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
  }

  .header-left {
      display: flex;
      align-items: center;
      gap: 16px;
  }

  .logo {
      background-color: #dc2626;
      color: white;
      padding: 8px 16px;
      border-radius: 4px;
      font-weight: bold;
      display: flex;
      align-items: center;
      gap: 8px;
  }

  .search-container {
      position: relative;
  }

  .search-input {
      background-color: #4b5563;
      color: white;
      padding: 8px 12px 8px 40px;
      border: none;
      border-radius: 4px;
      width: 300px;
      outline: none;
  }

  .search-input::placeholder {
      color: #9ca3af;
  }

  .search-icon {
      position: absolute;
      left: 12px;
      top: 50%;
      transform: translateY(-50%);
      width: 16px;
      height: 16px;
      opacity: 0.6;
  }

  .header-right {
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 14px;
  }

  /* Status Badge */
  .status-badge {
      background-color: #10b981;
      color: white;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
      display: flex;
      align-items: center;
      gap: 4px;
  }

  /* Layout */
  .container {
      display: flex;
      min-height: calc(100vh - 56px);
  }

  /* Sidebar */
  .sidebar {
      width: 256px;
      background-color: white;
      box-shadow: 2px 0 8px rgba(0, 0, 0, 0.1);
  }

  .nav-item {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px 24px;
      cursor: pointer;
      transition: background-color 0.2s;
      font-size: 14px;
      color: #6b7280;
  }

  .nav-item:hover {
      background-color: #f3f4f6;
  }

  .nav-item.active {
      background-color: #dc2626;
      color: white;
      font-weight: 600;
  }

  /* Main Content */
  .main-content {
      flex: 1;
      padding: 24px;
  }

  .page-header {
      margin-bottom: 24px;
  }

  .page-title {
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 8px;
  }

  .page-subtitle {
      color: #6b7280;
      font-size: 14px;
  }

  /* KPI Cards */
  .kpi-grid {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 16px;
      margin-bottom: 24px;
  }

  .kpi-card {
      background-color: white;
      padding: 16px;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      text-align: center;
  }

  .kpi-icon {
      font-size: 24px;
      margin-bottom: 8px;
  }

  .kpi-value {
      font-size: 24px;
      font-weight: bold;
      color: #374151;
      margin-bottom: 4px;
  }

  .kpi-label {
      font-size: 12px;
      color: #6b7280;
      text-transform: uppercase;
  }

  /* Grid Layout */
  .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
  }

  .card {
      background-color: white;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      padding: 24px;
  }

  .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      padding-bottom: 16px;
      border-bottom: 1px solid #e5e7eb;
  }

  .card-title {
      font-size: 16px;
      font-weight: 600;
      color: #374151;
  }

  /* Map Container */
  .map-container {
      height: 600px;
      background-color: #1f2937;
      border-radius: 8px;
      position: relative;
      overflow: hidden;
      background-image: 
          linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
          linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px);
      background-size: 20px 20px;
  }

  /* Map Controls */
  .map-controls {
      position: absolute;
      top: 10px;
      right: 10px;
      display: flex;
      flex-direction: column;
      gap: 8px;
      z-index: 20;
  }

  .map-btn {
      background-color: rgba(255, 255, 255, 0.95);
      border: none;
      padding: 8px;
      border-radius: 4px;
      cursor: pointer;
      width: 36px;
      height: 36px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 18px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      transition: all 0.2s;
  }

  .map-btn:hover {
      background-color: white;
      transform: scale(1.05);
  }

  /* Revenue Zones */
  .revenue-zone {
      position: absolute;
      border: 2px solid rgba(255, 255, 255, 0.3);
      cursor: pointer;
      transition: all 0.2s;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 11px;
      font-weight: 600;
      color: white;
      text-align: center;
  }

  .revenue-zone:hover {
      transform: scale(1.05);
      z-index: 10;
      border-color: white;
  }

  /* Revenue Level Colors */
  .revenue-highest { background-color: rgba(220, 38, 38, 0.8); }
  .revenue-high    { background-color: rgba(245, 158, 11, 0.8); }
  .revenue-medium  { background-color: rgba(251, 191, 36, 0.8); }
  .revenue-standard{ background-color: rgba(34, 197, 94, 0.8); }
  .revenue-low     { background-color: rgba(59, 130, 246, 0.8); }

  /* Form Styles */
  .form-section { margin-bottom: 24px; }
  .form-section-title {
      font-size: 14px; font-weight: 600; color: #374151; margin-bottom: 12px; text-transform: uppercase;
  }
  .form-group { margin-bottom: 16px; }
  .form-label { display: block; font-size: 14px; font-weight: 500; color: #374151; margin-bottom: 4px; }
  .form-label-required::after { content: " *"; color: #dc2626; }
  .form-input {
      width: 100%; padding: 8px 12px; border: 1px solid #e5e7eb; border-radius: 4px; font-size: 14px; transition: border-color 0.2s;
  }
  .form-input:focus { outline: none; border-color: #dc2626; }
  .form-select { width: 100%; padding: 8px 12px; border: 1px solid #e5e7eb; border-radius: 4px; font-size: 14px; background-color: white; cursor: pointer; }

  /* Button Styles */
  .btn { padding: 10px 20px; border: none; border-radius: 4px; font-size: 14px; font-weight: 600; cursor: pointer; transition: all 0.2s; text-transform: uppercase; }
  .btn-primary { background-color: #dc2626; color: white; }
  .btn-primary:hover { background-color: #b91c1c; }
  .btn-secondary { background-color: white; color: #374151; border: 1px solid #e5e7eb; }
  .btn-secondary:hover { background-color: #f3f4f6; }
  .btn-icon { display: inline-flex; align-items: center; gap: 8px; }

  /* Revenue Source Tags */
  .revenue-source-tags { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }
  .source-tag { background-color: #e5e7eb; color: #374151; padding: 6px 12px; border-radius: 20px; font-size: 12px; font-weight: 500; cursor: pointer; transition: all 0.2s; }
  .source-tag:hover { background-color: #d1d5db; }
  .source-tag.active { background-color: #dc2626; color: white; }

  /* COA Compliance Box */
  .coa-box { background-color: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 12px; margin-bottom: 16px; font-size: 13px; color: #1e40af; display: flex; align-items: center; gap: 8px; }

  /* Revenue Table */
  .revenue-table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 16px; }
  .revenue-table th { background-color: #f3f4f6; padding: 8px 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 1px solid #e5e7eb; }
  .revenue-table td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; }
  .revenue-table tr:hover { background-color: #f9fafb; }

  /* Performance Badge */
  .performance-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge-excellent { background-color: #d1fae5; color: #065f46; }
  .badge-good { background-color: #dbeafe; color: #1e40af; }
  .badge-average { background-color: #fef3c7; color: #92400e; }
  .badge-needs-improvement { background-color: #fee2e2; color: #991b1b; }

  /* Legend */
  .legend { display: flex; justify-content: center; gap: 24px; padding: 16px; background-color: #f9fafb; border-radius: 6px; margin-top: 16px; }
  .legend-item { display: flex; align-items: center; gap: 8px; font-size: 12px; cursor: pointer; padding: 4px; border-radius: 4px; transition: background-color 0.2s; }
  .legend-item:hover { background-color: #f3f4f6; }
  .legend-item.disabled { opacity: 0.5; }
  .legend-item.disabled .legend-dot { background: #e5e7eb !important; }
  .legend-color { width: 20px; height: 20px; border-radius: 4px; }

  /* Full width */
  .full-width { grid-column: 1 / -1; }

  /* Workflow Status */
  .workflow-container { background-color: #f9fafb; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
  .workflow-header { font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; margin-bottom: 12px; }
  .workflow-steps { display: flex; align-items: center; justify-content: space-between; position: relative; }
  .workflow-step { text-align: center; flex: 1; }
  .step-icon { width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 8px; font-size: 18px; font-weight: bold; }
  .step-icon.completed { background-color: #10b981; color: white; }
  .step-icon.active { background-color: #dc2626; color: white; }
  .step-icon.pending { background-color: #e5e7eb; color: #9ca3af; }
  .step-label { font-size: 12px; font-weight: 600; color: #374151; }
  .workflow-line { position: absolute; height: 2px; background-color: #e5e7eb; top: 20px; left: 33%; right: 33%; z-index: -1; }
  .workflow-line-active { background-color: #10b981; width: 33%; }

  /* Quick Stats */
  .quick-stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }
  .stat-card { background-color: #f9fafb; padding: 12px; border-radius: 6px; text-align: center; }
  .stat-value { font-size: 20px; font-weight: bold; color: #374151; }
  .stat-label { font-size: 11px; color: #6b7280; text-transform: uppercase; margin-top: 4px; }

  /* Date Range Grid */
  .date-range-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }

  /* Revenue Trend Chart Styles */
  .trend-chart-section { margin-top: 20px; background-color: white; border-radius: 8px; padding: 20px; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); border: 1px solid #e5e7eb; }
  .trend-chart-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
  .trend-chart-title { font-size: 18px; font-weight: 600; color: #111827; margin: 0; }
  .trend-chart-controls { display: flex; gap: 8px; align-items: center; }
  .trend-select { padding: 6px 12px; border: 1px solid #e5e7eb; border-radius: 4px; font-size: 13px; background-color: white; cursor: pointer; }
  .trend-btn { padding: 6px 10px; border: 1px solid #e5e7eb; border-radius: 4px; background-color: white; cursor: pointer; font-size: 16px; transition: all 0.2s; }
  .trend-btn:hover { background-color: #f3f4f6; transform: translateY(-1px); }
  .trend-summary-cards { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 20px; }
  .trend-card { background-color: #f9fafb; padding: 12px; border-radius: 6px; text-align: center; cursor: pointer; transition: all 0.2s; }
  .trend-card:hover { background-color: #f3f4f6; transform: translateY(-2px); box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); }
  .trend-card-value { font-size: 20px; font-weight: 700; color: #111827; margin-bottom: 4px; }
  .trend-card-label { font-size: 11px; color: #6b7280; text-transform: uppercase; }
  .trend-card-sublabel { font-size: 11px; color: #374151; margin-top: 2px; }
  .trend-card-change { font-size: 12px; font-weight: 600; margin-top: 4px; }
  .trend-card-change.positive { color: #10b981; }
  .trend-card-change.negative { color: #ef4444; }
  .chart-wrapper { position: relative; height: 350px; margin-bottom: 20px; padding: 10px; background-color: #fcfcfc; border-radius: 6px; border: 1px solid #f3f4f6; }
  .chart-legend-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; padding: 16px; background-color: #f9fafb; border-radius: 6px; }
  .legend-dot { width: 12px; height: 12px; border-radius: 50%; flex-shrink: 0; }
  .legend-label { flex: 1; color: #374151; }
  .legend-value { font-weight: 600; color: #111827; }

  @media (max-width: 1024px) {
      .trend-summary-cards { grid-template-columns: repeat(2, 1fr); }
      .chart-legend-grid { grid-template-columns: repeat(2, 1fr); }
  }

  @media (max-width: 768px) {
      .trend-chart-controls { flex-wrap: wrap; }
      .chart-wrapper { height: 250px; }
      .trend-summary-cards { grid-template-columns: repeat(2, 1fr); }
      .chart-legend-grid { grid-template-columns: 1fr; }
  }

  /* Revenue Code List */
  .revenue-code-list { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; margin-top: 8px; }
  .revenue-code-item { display: flex; align-items: center; gap: 8px; font-size: 12px; }
  .revenue-code-checkbox { cursor: pointer; }
`;
