// typescript-css.ts

const styles = {
  global: {
    '*': {
      margin: 0,
      padding: 0,
      boxSizing: 'border-box',
    },
    body: {
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      backgroundColor: '#f3f4f6',
      color: '#374151',
    },
  },
  header: {
    backgroundColor: '#374151',
    color: 'white',
    padding: '12px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  logo: {
    backgroundColor: '#dc2626',
    color: 'white',
    padding: '8px 16px',
    borderRadius: '4px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  searchContainer: {
    position: 'relative',
  },
  searchInput: {
    backgroundColor: '#4b5563',
    color: 'white',
    padding: '8px 12px 8px 40px',
    border: 'none',
    borderRadius: '4px',
    width: '300px',
    outline: 'none',
    '::placeholder': {
      color: '#9ca3af',
    },
  },
  searchIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '16px',
    height: '16px',
    opacity: 0.6,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    fontSize: '14px',
  },
  statusBadge: {
    backgroundColor: '#10b981',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  container: {
    display: 'flex',
    minHeight: 'calc(100vh - 56px)',
  },
  sidebar: {
    width: '256px',
    backgroundColor: 'white',
    boxShadow: '2px 0 8px rgba(0,0,0,0.1)',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 24px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '14px',
    color: '#6b7280',
    ':hover': {
      backgroundColor: '#f3f4f6',
    },
    '&.active': {
      backgroundColor: '#dc2626',
      color: 'white',
      fontWeight: 600,
    },
  },
  mainContent: {
    flex: 1,
    padding: '24px',
  },
  pageHeader: {
    marginBottom: '24px',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 600,
    marginBottom: '8px',
  },
  pageSubtitle: {
    color: '#6b7280',
    fontSize: '14px',
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '16px',
    marginBottom: '24px',
  },
  kpiCard: {
    backgroundColor: 'white',
    padding: '16px',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    textAlign: 'center',
  },
  kpiIcon: {
    fontSize: '24px',
    marginBottom: '8px',
  },
  kpiValue: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: '4px',
  },
  kpiLabel: {
    fontSize: '12px',
    color: '#6b7280',
    textTransform: 'uppercase',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '24px',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '16px',
    borderBottom: '1px solid #e5e7eb',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#374151',
  },
  mapContainer: {
    height: '600px',
    backgroundColor: '#1f2937',
    borderRadius: '8px',
    position: 'relative',
    overflow: 'hidden',
    backgroundImage: `
      linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)`,
    backgroundSize: '20px 20px',
  },
  mapControls: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    zIndex: 20,
  },
  mapBtn: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    border: 'none',
    padding: '8px',
    borderRadius: '4px',
    cursor: 'pointer',
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    transition: 'all 0.2s',
    ':hover': {
      backgroundColor: 'white',
      transform: 'scale(1.05)',
    },
  },
  revenueZone: {
    position: 'absolute',
    border: '2px solid rgba(255,255,255,0.3)',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    fontWeight: 600,
    color: 'white',
    textAlign: 'center',
    ':hover': {
      transform: 'scale(1.05)',
      zIndex: 10,
      borderColor: 'white',
    },
  },
  revenueHighest: {
    backgroundColor: 'rgba(220,38,38,0.8)',
  },
  revenueHigh: {
    backgroundColor: 'rgba(245,158,11,0.8)',
  },
  revenueMedium: {
    backgroundColor: 'rgba(251,191,36,0.8)',
  },
  revenueStandard: {
    backgroundColor: 'rgba(34,197,94,0.8)',
  },
  revenueLow: {
    backgroundColor: 'rgba(59,130,246,0.8)',
  },
  // ...continue for all other selectors following this pattern
};

export default styles;
